### ISSUE TITLE
Add support for declare-datatype

### ISSUE THREAD

**Issue by nblei** [ddsmt/ddSMT#19]
Currently doesn't support SMTLIB-2.6's declare-datatype.

**Comment by aniemetz** [comment]
Yes, datatypes are currently not supported. Due to limited capacities on our side, it's pretty much on the very bottom of the priority stack. We'd be happy to give guidance and review a PR that extends ddSMT with support for datatypes.

**Comment by aniemetz** [comment]
ddSMT now supports datatypes. Let us know if you miss certain datatype-specific simplifications that might be useful.

**Comment by nblei** [comment]
Awesome, and I didn't help at all :-)
